# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Florian PARRENO
author: Florian PARRENO
description: Florian PARRENO, Lead Développeur Symfony, Formateur Symfony dans la région de Montpellier
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://flohw.github.io" # the base hostname & protocol for your site
paginate: 5

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

sass:
  sass_dir: assets/scss/
  style: compressed

exclude:
  - assets/scss
  - vendor

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "single-post"
  -
    scope:
      path:            "**/*.pdf"
    values:
      sitemap:         false
