# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Florian PARRENO
email: flohwp@hotmail.fr
description: > # this means to ignore newlines until "baseurl:"
  La description de mon super site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://flohw.github.io" # the base hostname & protocol for your site
twitter_username: iFlohw
github_username:  flohw

# Build settings
markdown: kramdown
